# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96337c2e4772819b869db8d94a539cce1e962465781f0873ab723ffe6b4111f83735bf20ce2a35ce2af7c0544b6148a7dffedc56ad2511319cb1f32d8bcf1cfc

test:
  secret_key_base: d2d47e4aea4680074c916007df31248a97e2feae646cf27e79d93dfe3541da8110d8beb233cddfe71ca25d6becfa52397ea5698409d4a8457e2f9aeda8c43877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
